### ISSUE TITLE
VerifyPerceptionCategoryMethods.perceptionCategoryTest assertion failure

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/opentrafficsim#128]
`VerifyPerceptionCategoryMethods.perceptionCategotyTest()` (typo in the method name) in ots-core fails with an assertion error:

```
org.opentest4j.AssertionFailedError: Class class org.opentrafficsim.core.gtu.perception.DirectEgoPerception 
                does not have a field 'length*', nor wraps a perception category that does.
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at org.opentrafficsim.core.gtu.perception.VerifyPerceptionCategoryMethods.
                testGetter(VerifyPerceptionCategoryMethods.java:182)
	at org.opentrafficsim.core.gtu.perception.VerifyPerceptionCategoryMethods.
                perceptionCategotyTest(VerifyPerceptionCategoryMethods.java:124)
```

**Comment by WJSchakel** [comment]
Fixes for issues #125 and #126 have also fixed this issue.
